### ISSUE TITLE
Exports is not defined

### ISSUE THREAD

**Issue by Totemika** [basarat/typescript-script#3]
In the plunker example we get this error. Do you know how we should avoid this?

![image](https://cloud.githubusercontent.com/assets/4906291/23753118/87fe2eda-04d8-11e7-8d2d-f293b735cdb9.png)

**Comment by atsu85** [comment]
@Totemika, i stumbled upon this issue as well.
@basarat, I think readme could be improved with instructions for this problem - see my solution bellow.

# Problem
The problem appears because of generated module format, caused by module imports/exports.

# Solution
By replacing 
`import { SomeType } from 'someLib';`
statements with file reference, smth like
`/// <reference path="../../typings/custom/someLib.d.ts" />`
the problem disappeared at runtime.

As I had written the referenced type definitions in non-global format, my IDE TypeScript plugin showed me errors related to not being able to resolve `SomeType`, so i needed to convert the someLib.d.ts file into global format - that solved the problem

**Comment by basarat** [comment]
Short version: Don't use modules for script tags. Use only what is valid in a script tag :rose:
